spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ruoyi_vue_pro?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
###########################redis配置信息########################
  redis:
    database: 0         #redis数据库索引（默认为0）
    host: 127.0.0.1     #redis服务器地址
    port: 6379          #redis服务器端口
    password:           #redis服务器连接密码（默认为空）
    timeout: 10000      #过期时间
    lettuce:
      pool:
        max-active: 8    #连接池最大连接数（使用负值表示没有限制）默认 8
        max-wait: -1     #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8      #连接池中的最大空闲连接 默认 8
        min-idle: 0      #连接池中最小的空闲连接 默认 0
####################################kafka配置信息#####################################
####配置生产者信息#########
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      retries: 0            #发生错误后，消息重发的次数
      batch-size: 16384     #当有多个消息需要被发送到同一个分区时，生产者会把他们放在同一个批次里。该参数指定了一个批次可以使用的内存大小，按字节数计算
      buffer-memory: 33554432   #生产者内存缓冲区的大小
      key-serializer: org.apache.kafka.common.serialization.StringSerializer   #键的序列化方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
        #      value-serializer: org.apache.kafka.common.serialization.SringSerializer  #值的序列化方式
          #value-serializer: org.apache.kafka.common.serialization.UUIDDeserializer
      acks: 1
          # acks=0:生产者在成功写入消息前不会等待任何来自服务器的响应
         #acks=1:只要集群的首领节点收到消息，生产者就会收到一个来自服务器成功响应
         #acks=all:只有当所有参与复制的节点全部收到消息时，生产者才会收到一个来自服务器的成功响应
##配置消费者信息#######
    consumer:
      retries: 0            #发生错误后，消息重试的次数
      auto-commit-interval: 1H    #自动提交的时间间隔在spring boot2.x版本中这里采用的是值的类型为Duration需要符合特定的格式，如1s,1M,1H,1D
      auto-offset-reset: latest #该属性指定了消费者在读取一个没有偏移量的分区或者偏移量无效的情况下该作何处理：
        #latest(默认值)在偏移量无效的情况下，消费者将从最新的记录开始读取数据（在消费者启动之后生成的记录）
        #earliest:在偏移量无效的情况下，消费者将从起始位置读取分区的记录
      enable-auto-commit: false   #是否自动提交偏移量，默认值是true,为了避免出现重复数据和数据丢失，可以把它设置为false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer   #键的反序列化方式
      #value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      #group_id: console-consumer-33723
      group_id: topic.group1
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer   #值的反序列化方式
          #key-deserializer: com.cit.iomt.core.DevModelDeserializer
          #value-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
    listener:
      concurrency: 1   #在侦听器容器中运行的线程数
      #ack-mode: manual_immediate   #listner负责ack，每调用一次，就立即用commit
      ack-mode: TIME
      missing-topics-fatal: false

